project_id = "fphqfgxfeaylldpxjqan"

[functions.zap-responder]
verify_jwt = false

[functions.send-billing]
verify_jwt = false

[functions.mass-broadcast]
verify_jwt = false

[functions.update-user-password]
verify_jwt = false

[functions.scheduled-billing]
verify_jwt = false

[functions.evolution-webhook]
verify_jwt = false

[functions.meta-webhook]
verify_jwt = false

[functions.create-reseller]
verify_jwt = false

[functions.meta-oauth]
verify_jwt = false

[functions.meta-send-message]
verify_jwt = false
