project_id = "fphqfgxfeaylldpxjqan"

[functions.zap-responder]
verify_jwt = false

[functions.send-billing]
verify_jwt = false

[functions.mass-broadcast]
verify_jwt = false

[functions.update-user-password]
verify_jwt = false

[functions.scheduled-billing]
verify_jwt = false
