project_id = "fphqfgxfeaylldpxjqan"

[functions.zap-responder]
verify_jwt = false

[functions.send-billing]
verify_jwt = false

[functions.send-billing-batch]
verify_jwt = false

[functions.mass-broadcast]
verify_jwt = false

[functions.update-user-password]
verify_jwt = false

[functions.scheduled-billing]
verify_jwt = false

[functions.create-reseller]
verify_jwt = false

[functions.create-sub-reseller]
verify_jwt = false

[functions.renew-sub-reseller]
verify_jwt = false

[functions.meta-oauth]
verify_jwt = false

[functions.vplay-generate-test]
verify_jwt = false

[functions.xui-renew]
verify_jwt = false

[functions.cakto-webhook]
verify_jwt = false

[functions.daily-report]
verify_jwt = false

[functions.the-best-renew]
verify_jwt = false

[functions.rush-renew]
verify_jwt = false

[functions.natv-renew]
verify_jwt = false

[functions.vplay-renew]
verify_jwt = false
